AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create the IAM team IAM Roles in the
  Production AWS accounts.
Metadata:
  Source: https://github.com/mozilla-iam/infra-bootstrapping/tree/master/operations/aws-iam-roles-groups-and-policies
Resources:
  AWSFederatedAccountReadRole:
    Type: AWS::IAM::Role
    Metadata:
      Notes1: This read role permits users (not ec2 instances roles) in the AWS account
        identified by ProdAccountId using Federated Access.
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
              Effect: Allow
              Action: sts:AssumeRoleWithSAML
              Principal:
                Federated:
                  Fn::Sub: arn:aws:iam::${AWS::AccountId}:saml-provider/auth0-prod
              Condition:
                StringEquals:
                  SAML:aud: https://signin.aws.amazon.com/saml
                  SAML:iss: urn:auth.mozilla.auth0.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      RoleName: FederatedAWSAccountRead
  AWSFederatedAccountAdminRole:
    Type: AWS::IAM::Role
    Metadata:
      Notes1: This admin role permits users (not ec2 instances roles) in the AWS account
        identified by ProdAccountId
      Notes2: who've authenticated using federated access.
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
              Effect: Allow
              Action: sts:AssumeRoleWithSAML
              Principal:
                Federated:
                  Fn::Sub: arn:aws:iam::${AWS::AccountId}:saml-provider/auth0-prod
              Condition:
                StringEquals:
                  SAML:aud: https://signin.aws.amazon.com/saml
                  SAML:iss: urn:auth.mozilla.auth0.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: FederatedAWSAccountAdmin
