AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create the IAM team IAM Roles in the
  Production AWS accounts.
Metadata:
  Source: https://github.com/mozilla-iam/infra-bootstrapping/tree/master/operations/aws-iam-roles-groups-and-policies
Mappings:
  VariablesMap:
    AWSAccount:
      ProdAccountId: '320464205386'
Resources:
  AWSAccountReadRole:
    Type: AWS::IAM::Role
    Metadata:
      Notes1: This read role permits users (not ec2 instances roles) in the AWS account
        identified by ProdAccountId
      Notes2: who've authenticated with an MFA code to assume it. The role grants
        the user read permissions.
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: !Join
                - ':'
                - - 'arn:aws:iam:'
                  - !FindInMap
                    - VariablesMap
                    - AWSAccount
                    - ProdAccountId
                  - root
            Condition:
              StringEquals:
                aws:PrincipalType: User
              Bool:
                aws:MultiFactorAuthPresent: true
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      RoleName: AWSAccountRead
  AWSAccountAdminRole:
    Type: AWS::IAM::Role
    Metadata:
      Notes1: This admin role permits users (not ec2 instances roles) in the AWS account
        identified by ProdAccountId
      Notes2: who've authenticated with an MFA code to assume it. The role grants
        the user admin permissions.
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: !Join
                - ':'
                - - 'arn:aws:iam:'
                  - !FindInMap
                    - VariablesMap
                    - AWSAccount
                    - ProdAccountId
                  - root
            Condition:
              StringEquals:
                aws:PrincipalType: User
              Bool:
                aws:MultiFactorAuthPresent: true
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: AWSAccountAdmin
